######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 17 08:06:31 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . res
INCLUDEPATH += .

# Input
HEADERS += common.h IsoFile.hpp
FORMS += editor.ui opendialog.ui
SOURCES += main.cpp
RESOURCES += res/icons.qrc
