######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 17 08:35:21 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . res
INCLUDEPATH += .

# Input
HEADERS += common.h Editor.hpp IsoFile.hpp OpenDialog.hpp
FORMS += editor.ui opendialog.ui
SOURCES += Editor.cpp main.cpp OpenDialog.cpp
RESOURCES += res/icons.qrc
